# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/tom/prog/FAST

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/tom/prog/FAST

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tom/prog/FAST/CMakeFiles /home/tom/prog/FAST/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tom/prog/FAST/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named FAST

# Build rule for target.
FAST: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 FAST
.PHONY : FAST

# fast build rule for target.
FAST/fast:
	$(MAKE) -f CMakeFiles/FAST.dir/build.make CMakeFiles/FAST.dir/build
.PHONY : FAST/fast

sources/find_particules.o: sources/find_particules.cpp.o

.PHONY : sources/find_particules.o

# target to build an object file
sources/find_particules.cpp.o:
	$(MAKE) -f CMakeFiles/FAST.dir/build.make CMakeFiles/FAST.dir/sources/find_particules.cpp.o
.PHONY : sources/find_particules.cpp.o

sources/find_particules.i: sources/find_particules.cpp.i

.PHONY : sources/find_particules.i

# target to preprocess a source file
sources/find_particules.cpp.i:
	$(MAKE) -f CMakeFiles/FAST.dir/build.make CMakeFiles/FAST.dir/sources/find_particules.cpp.i
.PHONY : sources/find_particules.cpp.i

sources/find_particules.s: sources/find_particules.cpp.s

.PHONY : sources/find_particules.s

# target to generate assembly for a file
sources/find_particules.cpp.s:
	$(MAKE) -f CMakeFiles/FAST.dir/build.make CMakeFiles/FAST.dir/sources/find_particules.cpp.s
.PHONY : sources/find_particules.cpp.s

sources/link_particules.o: sources/link_particules.cpp.o

.PHONY : sources/link_particules.o

# target to build an object file
sources/link_particules.cpp.o:
	$(MAKE) -f CMakeFiles/FAST.dir/build.make CMakeFiles/FAST.dir/sources/link_particules.cpp.o
.PHONY : sources/link_particules.cpp.o

sources/link_particules.i: sources/link_particules.cpp.i

.PHONY : sources/link_particules.i

# target to preprocess a source file
sources/link_particules.cpp.i:
	$(MAKE) -f CMakeFiles/FAST.dir/build.make CMakeFiles/FAST.dir/sources/link_particules.cpp.i
.PHONY : sources/link_particules.cpp.i

sources/link_particules.s: sources/link_particules.cpp.s

.PHONY : sources/link_particules.s

# target to generate assembly for a file
sources/link_particules.cpp.s:
	$(MAKE) -f CMakeFiles/FAST.dir/build.make CMakeFiles/FAST.dir/sources/link_particules.cpp.s
.PHONY : sources/link_particules.cpp.s

sources/main.o: sources/main.cpp.o

.PHONY : sources/main.o

# target to build an object file
sources/main.cpp.o:
	$(MAKE) -f CMakeFiles/FAST.dir/build.make CMakeFiles/FAST.dir/sources/main.cpp.o
.PHONY : sources/main.cpp.o

sources/main.i: sources/main.cpp.i

.PHONY : sources/main.i

# target to preprocess a source file
sources/main.cpp.i:
	$(MAKE) -f CMakeFiles/FAST.dir/build.make CMakeFiles/FAST.dir/sources/main.cpp.i
.PHONY : sources/main.cpp.i

sources/main.s: sources/main.cpp.s

.PHONY : sources/main.s

# target to generate assembly for a file
sources/main.cpp.s:
	$(MAKE) -f CMakeFiles/FAST.dir/build.make CMakeFiles/FAST.dir/sources/main.cpp.s
.PHONY : sources/main.cpp.s

sources/point.o: sources/point.cpp.o

.PHONY : sources/point.o

# target to build an object file
sources/point.cpp.o:
	$(MAKE) -f CMakeFiles/FAST.dir/build.make CMakeFiles/FAST.dir/sources/point.cpp.o
.PHONY : sources/point.cpp.o

sources/point.i: sources/point.cpp.i

.PHONY : sources/point.i

# target to preprocess a source file
sources/point.cpp.i:
	$(MAKE) -f CMakeFiles/FAST.dir/build.make CMakeFiles/FAST.dir/sources/point.cpp.i
.PHONY : sources/point.cpp.i

sources/point.s: sources/point.cpp.s

.PHONY : sources/point.s

# target to generate assembly for a file
sources/point.cpp.s:
	$(MAKE) -f CMakeFiles/FAST.dir/build.make CMakeFiles/FAST.dir/sources/point.cpp.s
.PHONY : sources/point.cpp.s

sources/track.o: sources/track.cpp.o

.PHONY : sources/track.o

# target to build an object file
sources/track.cpp.o:
	$(MAKE) -f CMakeFiles/FAST.dir/build.make CMakeFiles/FAST.dir/sources/track.cpp.o
.PHONY : sources/track.cpp.o

sources/track.i: sources/track.cpp.i

.PHONY : sources/track.i

# target to preprocess a source file
sources/track.cpp.i:
	$(MAKE) -f CMakeFiles/FAST.dir/build.make CMakeFiles/FAST.dir/sources/track.cpp.i
.PHONY : sources/track.cpp.i

sources/track.s: sources/track.cpp.s

.PHONY : sources/track.s

# target to generate assembly for a file
sources/track.cpp.s:
	$(MAKE) -f CMakeFiles/FAST.dir/build.make CMakeFiles/FAST.dir/sources/track.cpp.s
.PHONY : sources/track.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... FAST"
	@echo "... edit_cache"
	@echo "... sources/find_particules.o"
	@echo "... sources/find_particules.i"
	@echo "... sources/find_particules.s"
	@echo "... sources/link_particules.o"
	@echo "... sources/link_particules.i"
	@echo "... sources/link_particules.s"
	@echo "... sources/main.o"
	@echo "... sources/main.i"
	@echo "... sources/main.s"
	@echo "... sources/point.o"
	@echo "... sources/point.i"
	@echo "... sources/point.s"
	@echo "... sources/track.o"
	@echo "... sources/track.i"
	@echo "... sources/track.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

